version: '3'

services:
  traefik:
    image: traefik:2.7
    container_name: appwrite-traefik
    restart: unless-stopped
    command:
      --api=true
      --api.dashboard=true
      --log.level=ERROR
      --providers.docker=true
      --providers.docker.exposedbydefault=false
      --entrypoints.web.address=:80
      --entrypoints.websecure.address=:443
      --entrypoints.web.http.redirections.entryPoint.to=websecure
      --entrypoints.web.http.redirections.entryPoint.scheme=https
      --certificatesresolvers.myresolver.acme.httpchallenge=true
      --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web
      --certificatesresolvers.myresolver.acme.email=admin@tudominio.com
      --certificatesresolvers.myresolver.acme.storage=acme.json
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - appwrite-config:/storage/config
      - appwrite-certificates:/storage/certificates
    networks:
      - gateway
      - appwrite

  appwrite:
    image: appwrite/appwrite:1.5.x
    container_name: appwrite
    restart: unless-stopped
    networks:
      - appwrite
    labels:
      - traefik.enable=true
      - traefik.docker.network=appwrite
      - traefik.constraint-label=appwrite
      # HTTP
      - traefik.http.routers.appwrite_http.entrypoints=web
      - traefik.http.routers.appwrite_http.rule=PathPrefix(`/`)
      - traefik.http.routers.appwrite_http.middlewares=redirectScheme
      # HTTPS
      - traefik.http.routers.appwrite_https.entrypoints=websecure
      - traefik.http.routers.appwrite_https.rule=PathPrefix(`/`)
      - traefik.http.routers.appwrite_https.tls=true
      - traefik.http.routers.appwrite_https.tls.certresolver=myresolver
      # Services
      - traefik.http.services.appwrite.loadbalancer.server.port=80
    volumes:
      - appwrite-uploads:/storage/uploads:rw
      - appwrite-cache:/storage/cache:rw
      - appwrite-config:/storage/config:rw
      - appwrite-certificates:/storage/certificates:rw
      - appwrite-functions:/storage/functions:rw
    environment:
      - _APP_ENV=production
      - _APP_LOCALE=es
      - _APP_OPTIONS_ABUSE=enabled
      - _APP_OPTIONS_FORCE_HTTPS=enabled
      - _APP_SYSTEM_EMAIL_NAME=Plataforma de Capacitación
      - _APP_SYSTEM_EMAIL_ADDRESS=noreply@tudominio.com
      - _APP_SYSTEM_RESPONSE_FORMAT=
      - _APP_SYSTEM_SECRET_KEY=cambia_esta_clave_secreta_por_una_segura
      - _APP_SYSTEM_REDIS_HOST=redis
      - _APP_SYSTEM_REDIS_PORT=6379
      - _APP_SYSTEM_REDIS_USER=
      - _APP_SYSTEM_REDIS_PASS=
      - _APP_DB_HOST=mariadb
      - _APP_DB_PORT=3306
      - _APP_DB_SCHEMA=appwrite
      - _APP_DB_USER=root
      - _APP_DB_PASS=password_segura_appwrite
      - _APP_SMTP_HOST=smtp.gmail.com
      - _APP_SMTP_PORT=587
      - _APP_SMTP_SECURE=tls
      - _APP_SMTP_USERNAME=tu_email@gmail.com
      - _APP_SMTP_PASSWORD=tu_password_de_aplicacion
      - _APP_USAGE_STATS=enabled
      - _APP_INFLUXDB_HOST=influxdb
      - _APP_INFLUXDB_PORT=8086
      - _APP_STORAGE_LIMIT=52428800
      - _APP_FUNCTIONS_SIZE_LIMIT=30000000
      - _APP_FUNCTIONS_TIMEOUT=900
      - _APP_FUNCTIONS_CONTAINERS=10
      - _APP_FUNCTIONS_CPUS=0
      - _APP_FUNCTIONS_MEMORY=0
      - _APP_FUNCTIONS_SWAP=0
      - _APP_FUNCTIONS_RUNTIMES=node-16.0,node-18.0,node-20.0,php-8.0,php-8.1,php-8.2,python-3.8,python-3.9,python-3.10,python-3.11,ruby-3.0,ruby-3.1,ruby-3.2
      - _APP_FUNCTIONS_INACTIVE_THRESHOLD=60
      - _APP_LOGGING_PROVIDER=
      - _APP_LOGGING_CONFIG=
      - _APP_MAINTENANCE_INTERVAL=86400
      - _APP_MAINTENANCE_RETENTION_CACHE=2592000
      - _APP_MAINTENANCE_RETENTION_EXECUTION=1209600
      - _APP_MAINTENANCE_RETENTION_AUDIT=1209600
      - _APP_MAINTENANCE_RETENTION_ABUSE=86400
      - _APP_MAINTENANCE_RETENTION_SCHEDULES=86400

  appwrite-realtime:
    image: appwrite/appwrite:1.5.x
    entrypoint: realtime
    container_name: appwrite-realtime
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=appwrite
      - traefik.constraint-label=appwrite
      - traefik.http.routers.appwrite_realtime_ws.entrypoints=websecure
      - traefik.http.routers.appwrite_realtime_ws.rule=PathPrefix(`/v1/realtime`)
      - traefik.http.routers.appwrite_realtime_ws.tls=true
      - traefik.http.routers.appwrite_realtime_ws.tls.certresolver=myresolver
      - traefik.http.services.appwrite_realtime_ws.loadbalancer.server.port=80
    networks:
      - appwrite
    environment:
      - _APP_ENV=production
      - _APP_OPTIONS_ABUSE=enabled
      - _APP_SYSTEM_SECRET_KEY=cambia_esta_clave_secreta_por_una_segura
      - _APP_SYSTEM_REDIS_HOST=redis
      - _APP_SYSTEM_REDIS_PORT=6379
      - _APP_SYSTEM_REDIS_USER=
      - _APP_SYSTEM_REDIS_PASS=
      - _APP_USAGE_STATS=enabled

  appwrite-worker-audits:
    image: appwrite/appwrite:1.5.x
    entrypoint: worker-audits
    container_name: appwrite-worker-audits
    restart: unless-stopped
    networks:
      - appwrite
    environment:
      - _APP_ENV=production
      - _APP_SYSTEM_SECRET_KEY=cambia_esta_clave_secreta_por_una_segura
      - _APP_DB_HOST=mariadb
      - _APP_DB_PORT=3306
      - _APP_DB_SCHEMA=appwrite
      - _APP_DB_USER=root
      - _APP_DB_PASS=password_segura_appwrite
      - _APP_LOGGING_PROVIDER=
      - _APP_LOGGING_CONFIG=

  appwrite-worker-webhooks:
    image: appwrite/appwrite:1.5.x
    entrypoint: worker-webhooks
    container_name: appwrite-worker-webhooks
    restart: unless-stopped
    networks:
      - appwrite
    environment:
      - _APP_ENV=production
      - _APP_SYSTEM_SECRET_KEY=cambia_esta_clave_secreta_por_una_segura
      - _APP_DB_HOST=mariadb
      - _APP_DB_PORT=3306
      - _APP_DB_SCHEMA=appwrite
      - _APP_DB_USER=root
      - _APP_DB_PASS=password_segura_appwrite
      - _APP_LOGGING_PROVIDER=
      - _APP_LOGGING_CONFIG=

  appwrite-worker-deletes:
    image: appwrite/appwrite:1.5.x
    entrypoint: worker-deletes
    container_name: appwrite-worker-deletes
    restart: unless-stopped
    networks:
      - appwrite
    environment:
      - _APP_ENV=production
      - _APP_SYSTEM_SECRET_KEY=cambia_esta_clave_secreta_por_una_segura
      - _APP_DB_HOST=mariadb
      - _APP_DB_PORT=3306
      - _APP_DB_SCHEMA=appwrite
      - _APP_DB_USER=root
      - _APP_DB_PASS=password_segura_appwrite
      - _APP_STORAGE_DEVICE=local
      - _APP_LOGGING_PROVIDER=
      - _APP_LOGGING_CONFIG=

  appwrite-worker-databases:
    image: appwrite/appwrite:1.5.x
    entrypoint: worker-databases
    container_name: appwrite-worker-databases
    restart: unless-stopped
    networks:
      - appwrite
    environment:
      - _APP_ENV=production
      - _APP_SYSTEM_SECRET_KEY=cambia_esta_clave_secreta_por_una_segura
      - _APP_DB_HOST=mariadb
      - _APP_DB_PORT=3306
      - _APP_DB_SCHEMA=appwrite
      - _APP_DB_USER=root
      - _APP_DB_PASS=password_segura_appwrite
      - _APP_LOGGING_PROVIDER=
      - _APP_LOGGING_CONFIG=

  appwrite-worker-builds:
    image: appwrite/appwrite:1.5.x
    entrypoint: worker-builds
    container_name: appwrite-worker-builds
    restart: unless-stopped
    networks:
      - appwrite
    environment:
      - _APP_ENV=production
      - _APP_SYSTEM_SECRET_KEY=cambia_esta_clave_secreta_por_una_segura
      - _APP_DB_HOST=mariadb
      - _APP_DB_PORT=3306
      - _APP_DB_SCHEMA=appwrite
      - _APP_DB_USER=root
      - _APP_DB_PASS=password_segura_appwrite
      - _APP_STORAGE_DEVICE=local
      - _APP_FUNCTIONS_RUNTIMES=node-16.0,node-18.0,node-20.0,php-8.0,php-8.1,php-8.2,python-3.8,python-3.9,python-3.10,python-3.11,ruby-3.0,ruby-3.1,ruby-3.2
      - _APP_FUNCTIONS_INACTIVE_THRESHOLD=60
      - _APP_LOGGING_PROVIDER=
      - _APP_LOGGING_CONFIG=

  appwrite-worker-certificates:
    image: appwrite/appwrite:1.5.x
    entrypoint: worker-certificates
    container_name: appwrite-worker-certificates
    restart: unless-stopped
    networks:
      - appwrite
    environment:
      - _APP_ENV=production
      - _APP_SYSTEM_SECRET_KEY=cambia_esta_clave_secreta_por_una_segura
      - _APP_DB_HOST=mariadb
      - _APP_DB_PORT=3306
      - _APP_DB_SCHEMA=appwrite
      - _APP_DB_USER=root
      - _APP_DB_PASS=password_segura_appwrite
      - _APP_STORAGE_DEVICE=local
      - _APP_LOGGING_PROVIDER=
      - _APP_LOGGING_CONFIG=

  appwrite-worker-functions:
    image: appwrite/appwrite:1.5.x
    entrypoint: worker-functions
    container_name: appwrite-worker-functions
    restart: unless-stopped
    networks:
      - appwrite
    environment:
      - _APP_ENV=production
      - _APP_SYSTEM_SECRET_KEY=cambia_esta_clave_secreta_por_una_segura
      - _APP_SYSTEM_REDIS_HOST=redis
      - _APP_SYSTEM_REDIS_PORT=6379
      - _APP_SYSTEM_REDIS_USER=
      - _APP_SYSTEM_REDIS_PASS=
      - _APP_DB_HOST=mariadb
      - _APP_DB_PORT=3306
      - _APP_DB_SCHEMA=appwrite
      - _APP_DB_USER=root
      - _APP_DB_PASS=password_segura_appwrite
      - _APP_FUNCTIONS_RUNTIMES=node-16.0,node-18.0,node-20.0,php-8.0,php-8.1,php-8.2,python-3.8,python-3.9,python-3.10,python-3.11,ruby-3.0,ruby-3.1,ruby-3.2
      - _APP_FUNCTIONS_SIZE_LIMIT=30000000
      - _APP_FUNCTIONS_TIMEOUT=900
      - _APP_FUNCTIONS_CONTAINERS=10
      - _APP_FUNCTIONS_CPUS=0
      - _APP_FUNCTIONS_MEMORY=0
      - _APP_FUNCTIONS_SWAP=0
      - _APP_FUNCTIONS_INACTIVE_THRESHOLD=60
      - DOCKERHUB_PULL_USERNAME=
      - DOCKERHUB_PULL_PASSWORD=
      - _APP_LOGGING_PROVIDER=
      - _APP_LOGGING_CONFIG=

  appwrite-worker-mails:
    image: appwrite/appwrite:1.5.x
    entrypoint: worker-mails
    container_name: appwrite-worker-mails
    restart: unless-stopped
    networks:
      - appwrite
    environment:
      - _APP_ENV=production
      - _APP_SYSTEM_SECRET_KEY=cambia_esta_clave_secreta_por_una_segura
      - _APP_SYSTEM_EMAIL_NAME=Plataforma de Capacitación
      - _APP_SYSTEM_EMAIL_ADDRESS=noreply@tudominio.com
      - _APP_SMTP_HOST=smtp.gmail.com
      - _APP_SMTP_PORT=587
      - _APP_SMTP_SECURE=tls
      - _APP_SMTP_USERNAME=tu_email@gmail.com
      - _APP_SMTP_PASSWORD=tu_password_de_aplicacion
      - _APP_LOGGING_PROVIDER=
      - _APP_LOGGING_CONFIG=

  appwrite-worker-messaging:
    image: appwrite/appwrite:1.5.x
    entrypoint: worker-messaging
    container_name: appwrite-worker-messaging
    restart: unless-stopped
    networks:
      - appwrite
    environment:
      - _APP_ENV=production
      - _APP_SYSTEM_SECRET_KEY=cambia_esta_clave_secreta_por_una_segura
      - _APP_DB_HOST=mariadb
      - _APP_DB_PORT=3306
      - _APP_DB_SCHEMA=appwrite
      - _APP_DB_USER=root
      - _APP_DB_PASS=password_segura_appwrite
      - _APP_LOGGING_PROVIDER=
      - _APP_LOGGING_CONFIG=

  appwrite-worker-migrations:
    image: appwrite/appwrite:1.5.x
    entrypoint: worker-migrations
    container_name: appwrite-worker-migrations
    restart: unless-stopped
    networks:
      - appwrite
    environment:
      - _APP_ENV=production
      - _APP_SYSTEM_SECRET_KEY=cambia_esta_clave_secreta_por_una_segura
      - _APP_DB_HOST=mariadb
      - _APP_DB_PORT=3306
      - _APP_DB_SCHEMA=appwrite
      - _APP_DB_USER=root
      - _APP_DB_PASS=password_segura_appwrite
      - _APP_LOGGING_PROVIDER=
      - _APP_LOGGING_CONFIG=

  appwrite-schedule:
    image: appwrite/appwrite:1.5.x
    entrypoint: schedule
    container_name: appwrite-schedule
    restart: unless-stopped
    networks:
      - appwrite
    environment:
      - _APP_ENV=production
      - _APP_SYSTEM_SECRET_KEY=cambia_esta_clave_secreta_por_una_segura
      - _APP_DB_HOST=mariadb
      - _APP_DB_PORT=3306
      - _APP_DB_SCHEMA=appwrite
      - _APP_DB_USER=root
      - _APP_DB_PASS=password_segura_appwrite

  mariadb:
    image: mariadb:10.7
    container_name: appwrite-mariadb
    restart: unless-stopped
    networks:
      - appwrite
    volumes:
      - appwrite-mariadb:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=password_segura_appwrite
      - MYSQL_DATABASE=appwrite
      - MYSQL_USER=appwrite
      - MYSQL_PASSWORD=password_segura_appwrite

  redis:
    image: redis:7.0-alpine
    container_name: appwrite-redis
    restart: unless-stopped
    command: >
      redis-server
      --maxmemory            512mb
      --maxmemory-policy     allkeys-lru
      --maxmemory-samples    5
    networks:
      - appwrite
    volumes:
      - appwrite-redis:/data:rw

  influxdb:
    image: appwrite/influxdb:1.5.x
    container_name: appwrite-influxdb
    restart: unless-stopped
    networks:
      - appwrite
    volumes:
      - appwrite-influxdb:/var/lib/influxdb:rw

networks:
  gateway:
  appwrite:

volumes:
  appwrite-mariadb:
  appwrite-redis:
  appwrite-cache:
  appwrite-uploads:
  appwrite-certificates:
  appwrite-functions:
  appwrite-builds:
  appwrite-config:
  appwrite-influxdb:
